/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elmfer_cnmcu_mcu_modules_CNUART */

#ifndef _Included_com_elmfer_cnmcu_mcu_modules_CNUART
#define _Included_com_elmfer_cnmcu_mcu_modules_CNUART
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNUART
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNUART_size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNUART
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNUART_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNUART
 * Method:    shouldInterrupt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNUART_shouldInterrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNUART
 * Method:    registerData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNUART_registerData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNUART
 * Method:    write
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNUART_write
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNUART
 * Method:    read
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNUART_read
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
