/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elmfer_cnmcu_cpp_NativesUtils */

#ifndef _Included_com_elmfer_cnmcu_cpp_NativesUtils
#define _Included_com_elmfer_cnmcu_cpp_NativesUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elmfer_cnmcu_cpp_NativesUtils
 * Method:    getByteBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_elmfer_cnmcu_cpp_NativesUtils_getByteBufferAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
