/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elmfer_cnmcu_mesh_Meshes */

#ifndef _Included_com_elmfer_cnmcu_mesh_Meshes
#define _Included_com_elmfer_cnmcu_mesh_Meshes
#ifdef __cplusplus
extern "C" {
#endif
#undef com_elmfer_cnmcu_mesh_Meshes_POSITION_COMPONENTS
#define com_elmfer_cnmcu_mesh_Meshes_POSITION_COMPONENTS 3L
#undef com_elmfer_cnmcu_mesh_Meshes_NORMAL_COMPONENTS
#define com_elmfer_cnmcu_mesh_Meshes_NORMAL_COMPONENTS 3L
#undef com_elmfer_cnmcu_mesh_Meshes_COLOR_COMPONENTS
#define com_elmfer_cnmcu_mesh_Meshes_COLOR_COMPONENTS 4L
#undef com_elmfer_cnmcu_mesh_Meshes_UV_COMPONENTS
#define com_elmfer_cnmcu_mesh_Meshes_UV_COMPONENTS 2L
#undef com_elmfer_cnmcu_mesh_Meshes_FACE_INDICIES
#define com_elmfer_cnmcu_mesh_Meshes_FACE_INDICIES 4L
/*
 * Class:     com_elmfer_cnmcu_mesh_Meshes
 * Method:    parsePLY
 * Signature: ([BLcom/elmfer/cnmcu/mesh/Mesh;)V
 */
JNIEXPORT void JNICALL Java_com_elmfer_cnmcu_mesh_Meshes_parsePLY
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
