/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elmfer_cnmcu_mcu_modules_CNEL */

#ifndef _Included_com_elmfer_cnmcu_mcu_modules_CNEL
#define _Included_com_elmfer_cnmcu_mcu_modules_CNEL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    iclRegistersData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_iclRegistersData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    iflRegistersData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_iflRegistersData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    triggerEvent
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_triggerEvent
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    shouldInterrupt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_shouldInterrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    read
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_read
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNEL
 * Method:    write
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNEL_write
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
