/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elmfer_cnmcu_mcu_modules_CNGPIO */

#ifndef _Included_com_elmfer_cnmcu_mcu_modules_CNGPIO
#define _Included_com_elmfer_cnmcu_mcu_modules_CNGPIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    pvFrontData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_pvFrontData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    pvBackData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_pvBackData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    dirData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_dirData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    intData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_intData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    iflData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_iflData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    read
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_read
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    write
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_write
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_elmfer_cnmcu_mcu_modules_CNGPIO
 * Method:    shouldInterrupt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_elmfer_cnmcu_mcu_modules_CNGPIO_shouldInterrupt
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
