name: Publish on GitHub, CurseForge & Modrinth

on: workflow_dispatch

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  MOD_VERSION: 0.0.10a
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  PRODUCTION: true

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            files: |
              build/natives/libcnmcu*
              vasm/vasm6502_oldstyle-linux-x64
              vasm/vobjdump-linux-x64
          - os: windows-latest
            files: |
              build/natives/Release/libcnmcu*
              vasm/vasm6502_oldstyle-windows-x64.exe
              vasm/vobjdump-windows-x64.exe
              vasm/cygwin1.dll
          - os: macos-latest
            files: |
              build/natives/libcnmcu*
              vasm/vasm6502_oldstyle-macos-x64
              vasm/vobjdump-macos-x64

    runs-on: ${{ matrix.os }}
    needs: validate

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Save Version
        run: ./gradlew saveVersion --console=plain

      - name: Commit updated mod version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update mod version to ${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"
          file_pattern: "gradle.properties *CodeNodeMicrocontrollers.java *fabric.mod.json"

      - name: Build Mod
        run: ./gradlew build --console=plain

      - name: Publish Mod (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: x3ZXt0cm
          modrinth-token: ${{ env.MODRINTH_TOKEN }}

          curseforge-id: 1011557
          curseforge-token: ${{ env.CURSEFORGE_TOKEN }}

          github-token: ${{ env.GITHUB_TOKEN }}

          name: "CodeNode Microcontrollers v${{ env.MOD_VERSION }} for Minecraft ${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"
          version-type: alpha
          
          loaders: fabric
          game-versions: "${{ env.MINECRAFT_VERSION }}"

      - name: Compile Natives
        run: ./gradlew compileNatives --console=plain

      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.files }}
          tag_name: "${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"